#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

restore0Dir # ths line creates the folder 0 from the folder 0.org

#Run blockMesh
runApplication blockMesh

cp -fr 0/polyMesh/points constant/polyMesh/points

# Create the wave probes
runApplication waveGaugesNProbes

# Compute the wave parameters
runApplication setWaveParameters

# Create the wave probes
runApplication waveGaugesNProbes

# Define relaxation zones (only needed if you want to visualize the resulting layout)
runApplication relaxationZoneLayout

# Set the alpha field according to wave theory
#runApplication setWaveField

# Set the alpha field according to setFieldsDict
#runApplication setFields