#!/bin/bash


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

nProc=20


#Decompose case again
runApplication decomposePar

# Renumber meshto get a more diagonal system
renumber_application="mpirun --oversubscribe -np $nProc renumberMesh -overwrite -parallel"
runApplication $renumber_application
mv log.mpirun log.renumberMesh
# Set solver name

solver="mpirun --oversubscribe -np $nProc waveDyMFoam -parallel"

# Run the solver
runApplication $solver
mv log.mpirun log.waveDyMFoam
#------------------------------------------------------------------------------
