#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Recontruct case
runApplication reconstructPar

# Reconstruct logs
runApplication foamLog log.waveDyMFoam
#############################################################
