#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Use the correct decomposeParDict
rm ./system/decomposeParDict
cp ./system/decomposeParDict_solver ./system/decomposeParDict

nProc=$(getNumberOfProcessors)

#Decompose case again
runApplication decomposePar

# Renumber meshto get a more diagonal system
renumber_application="mpirun -np $nProc renumberMesh -overwrite -parallel"
runApplication $renumber_application
mv log.mpirun log.renumberMesh

# Host name
#cat $PBS_NODEFILE 
#(
#for host in `cat $PBS_NODEFILE | sort -u -V`
#do
 #    count=`grep $host $PBS_NODEFILE | wc -l`
 #    echo $host cpu=$count
#done
#
#) > host_file
#cat host_file

# Set solver name
#solver="mpirun -np $nProc --hostfile host_file waveDyMFoam -parallel"
solver="mpirun --oversubscribe -np $nProc waveDyMFoam -parallel"

# Run the solver
runApplication $solver
mv log.mpirun log.waveDyMFoam