#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

restore0Dir # ths line creates the folder 0 from the folder 0.org

#Mesh
runApplication blockMesh
runApplication snappyHexMesh -overwrite

sed -i 's/symmetry/empty/g' 0/U
sed -i 's/symmetry/empty/g' 0/p_rgh
sed -i 's/symmetry/empty/g' 0/alpha.water
sed -i 's/symmetry/empty/g' constant/polyMesh/boundary

#wave probes
runApplication waveGaugesNProbes

#wave parameters
runApplication setWaveParameters

runApplication waveGaugesNProbes
 
runApplication relaxationZoneLayout

runApplication setWaveField