#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application="mpirun --oversubscribe -np 16 waveFoam -parallel"

runApplication decomposePar

runApplication $application

runApplication reconstructPar

runApplication foamLog log.mpirun