#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Reconstruct logs
runApplication foamLog log.waveDyMFoam

# Recontruct case
runApplication reconstructPar

rm -rf process*

