#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication snappyHexMesh -overwrite
#runApplication waveGaugesNProbes
runApplication setWaveParameters
runApplication relaxationZoneLayout
restore0Dir
runApplication setFields
cp -fr 0/polyMesh/points constant/polyMesh/points
